stages:
  - test
  - deploy
image: node:8.11.3
before_script:
  - npm install --global force-dev-tool --silent &>/dev/null
  - mkdir -p /sf-project && cd /sf-project
  - force-dev-tool remote add production vitaliy.paliy@ctdev.io 080494VpV https://login.salesforce.com 
  - force-dev-tool fetch --progress production
  - force-dev-tool package -a production
  - force-dev-tool retrieve production
cache:
  paths:
    - /usr/local/lib/node_modules
    - /sf-project
  untracked: true

list_folder:
  stage: test
  script:
    - cd /sf-project
    - force-dev-tool login production
    - ls -l
    - git init
    - git add . 
    - git remote add origin https://vitaliy.paliy:080494VpV@gitlab.com/vitaliy.paliy/test.git
    - git checkout -b deploy
    - git add .
    - git config --global user.email "vitaliy.paliy@ctdev.io"
    - git config --global user.name "Vitaliy Paliy"
    - git config --global user.username "vitaliy.paliy"
    - git config --global user.password "080494VpV"
    - git fetch --all
    - git commit -m "deploy_commit"
    - git diff --no-renames --name-only remotes/origin/master deploy
    - git diff --no-renames remotes/origin/master deploy | force-dev-tool changeset create deploy
#test_deploy_development:
 # stage: test
  #script:
   # - force-dev-tool deploy -ct development

#test_deploy_production:
#  stage: test
#  allow_failure: true
#  script:
#    - force-dev-tool deploy -ct production

#deploy_development:
#  stage: deploy
#  environment: development
#  only:
#   - develop
#  script:
#    - force-dev-tool deploy development

#deploy_production:
#  stage: deploy
#  environment: production
 # when: manual
 # script:
#    # The -t makes sure we run tests
 #   - force-dev-tool deploy -t production